import type { Workflow } from '@/types';

export const WORKFLOW_TEMPLATES: Omit<Workflow, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Feature Development Pipeline',
    description: 'Complete feature development with coding, testing, and review',
    repository: '',
    agents: [],
    status: 'draft',
    nodes: [
      {
        id: 'start',
        type: 'input',
        position: { x: 250, y: 50 },
        data: { label: 'Start' },
      },
      {
        id: 'coder',
        type: 'agent',
        position: { x: 250, y: 150 },
        data: { label: 'Code Implementation', agentType: 'coder' },
      },
      {
        id: 'parallel',
        type: 'parallel',
        position: { x: 250, y: 250 },
        data: { label: 'Parallel Testing', branches: 2 },
      },
      {
        id: 'unit-test',
        type: 'agent',
        position: { x: 100, y: 350 },
        data: { label: 'Unit Tests', agentType: 'tester' },
      },
      {
        id: 'integration-test',
        type: 'agent',
        position: { x: 400, y: 350 },
        data: { label: 'Integration Tests', agentType: 'tester' },
      },
      {
        id: 'reviewer',
        type: 'agent',
        position: { x: 250, y: 450 },
        data: { label: 'Code Review', agentType: 'reviewer' },
      },
      {
        id: 'condition',
        type: 'condition',
        position: { x: 250, y: 550 },
        data: { label: 'Quality Check', condition: 'tests_passed && review_approved' },
      },
      {
        id: 'documenter',
        type: 'agent',
        position: { x: 250, y: 650 },
        data: { label: 'Generate Docs', agentType: 'documenter' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start', target: 'coder' },
      { id: 'e2', source: 'coder', target: 'parallel' },
      { id: 'e3', source: 'parallel', target: 'unit-test' },
      { id: 'e4', source: 'parallel', target: 'integration-test' },
      { id: 'e5', source: 'unit-test', target: 'reviewer' },
      { id: 'e6', source: 'integration-test', target: 'reviewer' },
      { id: 'e7', source: 'reviewer', target: 'condition' },
      { id: 'e8', source: 'condition', target: 'documenter', sourceHandle: 'true' },
    ],
  },
  {
    name: 'Bug Fix Workflow',
    description: 'Analyze, fix, test, and document bug fixes',
    repository: '',
    agents: [],
    status: 'draft',
    nodes: [
      {
        id: 'start',
        type: 'input',
        position: { x: 250, y: 50 },
        data: { label: 'Bug Report' },
      },
      {
        id: 'analyst',
        type: 'agent',
        position: { x: 250, y: 150 },
        data: { label: 'Analyze Issue', agentType: 'analyst' },
      },
      {
        id: 'coder',
        type: 'agent',
        position: { x: 250, y: 250 },
        data: { label: 'Implement Fix', agentType: 'coder' },
      },
      {
        id: 'tester',
        type: 'agent',
        position: { x: 250, y: 350 },
        data: { label: 'Test Fix', agentType: 'tester' },
      },
      {
        id: 'documenter',
        type: 'agent',
        position: { x: 250, y: 450 },
        data: { label: 'Update Docs', agentType: 'documenter' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start', target: 'analyst' },
      { id: 'e2', source: 'analyst', target: 'coder' },
      { id: 'e3', source: 'coder', target: 'tester' },
      { id: 'e4', source: 'tester', target: 'documenter' },
    ],
  },
  {
    name: 'Code Refactoring',
    description: 'Iterative code refactoring with quality checks',
    repository: '',
    agents: [],
    status: 'draft',
    nodes: [
      {
        id: 'start',
        type: 'input',
        position: { x: 250, y: 50 },
        data: { label: 'Start' },
      },
      {
        id: 'loop',
        type: 'loop',
        position: { x: 250, y: 150 },
        data: { label: 'Refactor Iterations', iterations: 3 },
      },
      {
        id: 'analyst',
        type: 'agent',
        position: { x: 250, y: 250 },
        data: { label: 'Analyze Code', agentType: 'analyst' },
      },
      {
        id: 'coder',
        type: 'agent',
        position: { x: 250, y: 350 },
        data: { label: 'Refactor Code', agentType: 'coder' },
      },
      {
        id: 'reviewer',
        type: 'agent',
        position: { x: 250, y: 450 },
        data: { label: 'Review Changes', agentType: 'reviewer' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start', target: 'loop' },
      { id: 'e2', source: 'loop', target: 'analyst' },
      { id: 'e3', source: 'analyst', target: 'coder' },
      { id: 'e4', source: 'coder', target: 'reviewer' },
    ],
  },
  {
    name: 'Documentation Generation',
    description: 'Comprehensive documentation for codebase',
    repository: '',
    agents: [],
    status: 'draft',
    nodes: [
      {
        id: 'start',
        type: 'input',
        position: { x: 250, y: 50 },
        data: { label: 'Start' },
      },
      {
        id: 'analyst',
        type: 'agent',
        position: { x: 250, y: 150 },
        data: { label: 'Analyze Codebase', agentType: 'analyst' },
      },
      {
        id: 'parallel',
        type: 'parallel',
        position: { x: 250, y: 250 },
        data: { label: 'Generate Docs', branches: 3 },
      },
      {
        id: 'api-docs',
        type: 'agent',
        position: { x: 50, y: 350 },
        data: { label: 'API Docs', agentType: 'documenter' },
      },
      {
        id: 'readme',
        type: 'agent',
        position: { x: 250, y: 350 },
        data: { label: 'README', agentType: 'documenter' },
      },
      {
        id: 'guides',
        type: 'agent',
        position: { x: 450, y: 350 },
        data: { label: 'User Guides', agentType: 'documenter' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start', target: 'analyst' },
      { id: 'e2', source: 'analyst', target: 'parallel' },
      { id: 'e3', source: 'parallel', target: 'api-docs' },
      { id: 'e4', source: 'parallel', target: 'readme' },
      { id: 'e5', source: 'parallel', target: 'guides' },
    ],
  },
];
